#!/usr/bin/env python
'''
command to summarize a vasp calculation in a directory

usage:
jaspsum
   this will summarize the calculation in the current directory

jaspsum directoryname
   this will summarize the calculation in the directoryname
'''
import os, sys
from jasp import *
from optparse import OptionParser

parser = OptionParser(usage='ncsum',
                      version='0.1')
parser.add_option('-d',
                  nargs=0,
                  help = 'turn debug on')

options,args = parser.parse_args()

if len(args) == 0:
    dirs = ['.']
else:
    dirs = args

if options.d is not None:
    debug = logging.DEBUG
else:
    debug = None


for d in dirs:
    with jasp(d, debug=debug) as calc:
        print calc
