#!/usr/bin/env python
'''
command to summarize a vasp calculation in a directory

usage:
jaspsum
   this will summarize the calculation in the current directory

jaspsum directoryname
   this will summarize the calculation in the directoryname
'''
import os, sys
from jasp import *
from optparse import OptionParser

parser = OptionParser(usage='ncsum',
                      version='0.1')
parser.add_option('-d',
                  nargs=0,
                  help = 'turn debug on')

parser.add_option('-p',
                  nargs=0,
                  help = 'plot in ag')

parser.add_option('-t',
                  nargs=0,
                  help = 'plot trajectory')

parser.add_option('-r',
                  nargs=0,
                  help = 'prints code to make a new calculation')

parser.add_option('-j',
                  nargs=0,
                  help = 'prints json representation')

parser.add_option('-x',
                  nargs=0,
                  help = 'prints xml representation')

options,args = parser.parse_args()

if len(args) == 0:
    dirs = ['.']
else:
    dirs = args

if options.d is not None:
    debug = logging.DEBUG
else:
    debug = None

for d in dirs:
    with jasp(d, debug=debug) as calc:

        if options.t is not None:
            xd = xdat2traj('out.traj',calc=calc)
            xd.convert()
            os.system('ag out.traj; rm out.traj')

        if options.p is not None:
            atoms = calc.get_atoms()
            from ase.visualize import view
            view(atoms)

        if options.r is not None:
            print repr(calc)
        elif options.j is not None:
            from serialize import *
            print calc.json
        elif options.x is not None:
            from serialize import *
            print calc.xml
        else:
            print calc
