=jasp= is an extension module for ase.calculators.vasp.  Its primary purpose is smarter restarting capability, and job management/workflow, but it also has some enhanced capability too.

1. jasp automatically changes into the calculation directory to run jobs, and automatically changes back out when it is done.
2. jasp automatically submits jobs to the queue, and supports parallel and multiprocessing jobs.
3. jasp supports a lot more data extraction than ase.calculators.vasp.

jasp requires python 2.6+ to work, and the latest svn version of ase.

* Examples of using jasp
see http://github.com/jkitchin/dft-book

* Long-term plans for jasp
Everything that is in jasp may eventually be incorporated into ase.calculators.vasp. jasp will probably always be further on the development cycle than the ase.calculators.vasp. We try advanced concepts in workflow in jasp that may never be suitable for ase. We try using the latest features of python to see if it makes running calculations easier, faster or better in some way. ase strives to maintain a lot of compatibility with older python versions. jasp will not be constrained this way.
